Migrated documentation from Jupyter to Documenter.jl
sisl/BayesNets.jl pull request #127
Opened 2021-05-03 20:12 UTC by dwijenchawra

Migrated docs to Documenter.jl and updated github deployment workflows.

2021-05-03 21:23 UTC, mykelk requested changes
Minor change requested.

2021-05-03 21:23 UTC, mykelk commented on README.md
> +Please read the [documentation](https://dwijenchawra.github.io/BayesNets.jl/dev/index.html).
This needs to be updated.

2021-05-03 21:58 UTC, dwijenchawra commented on README.md
> +Please read the [documentation](https://dwijenchawra.github.io/BayesNets.jl/dev/index.html).
Fixed.

2021-05-03 22:00 UTC, dwijenchawra commented
There is a test for documentation that looks for the old Jupyter notebook, is that still necessary? The old notebook was moved to the docs folder for easy access, should it remain there or be deleted?

2021-05-03 22:01 UTC, mykelk commented
Cool. I'm good to merge. I was thinking it would be good to have @tawheeler do a quick skim before merging.

2021-05-03 22:01 UTC, mykelk commented
Maybe keep the notebook there for testing purposes. It helps with code coverage. We can move the tests later on.

2021-05-05 15:57 UTC, tawheeler commented
Moving to Documenter.jl is a really good idea. I like that images can be generated from the markdown. Thanks!

2021-05-05 16:00 UTC, mykelk commented
It looks like there is a failure here according to travis:
```
LoadError: SystemError: opening file "/home/travis/build/sisl/BayesNets.jl/doc/BayesNets.ipynb": No such file or directory
```
Can we make sure that file is added back? Once that's done, let's get this merged!

2021-05-05 16:27 UTC, dwijenchawra commented
There was a refactor needed in the tests files, we changed the name of the doc folder to docs because thats the way it was structured in both FreudenthalTriangulation and the Documenter docs. Both builds have passed now so I think we are good to go as well!

2021-05-05 16:30 UTC, merged